### ISSUE TITLE
[HELP] 1 redis, 2 workers pool, somehow jobs from second pool is not running

### ISSUE THREAD

**Issue by hendralimmm** [gocraft/work#100]
so lets say i have 1 redis, and create  2 workers pools -> each workers pool will have their own binary,
which we will use those binary for different product, binary 1 will process product A, binary 2 will process product B..

for some reason all job that go into binary 2 (second workers pool) is not working, it always go to dead jobs.. please help..

![image](https://user-images.githubusercontent.com/28975056/40533285-6eabfae2-602c-11e8-8dd9-8bbae554e47b.png)

![image](https://user-images.githubusercontent.com/28975056/40533334-965009da-602c-11e8-9313-4dda85c9b591.png)

it always say this 'unknown job when requeueing' (only happens to my second workers pools), first workers pool is running fine.

If i change the usage like these: 1 binary for all products it's working for single server, but the problem is i have 2 servers that means i have 1 identical binary in each server and somehow all jobs go to dead jobs.. 

In case u want to reproduce the issue, just try to make 1 redis and create 2 worker pools, try to run the program, in my case second worker pool's job will go to dead jobs.

note : i am using 'enqueuer.EnqueueIn' to schedule my jobs in future.. i really need to make this work..

**Comment by hendralimmm** [comment]
@shdunning

**Comment by doxxx** [comment]
I'm encountering this same problem. @hendralimmm did you find a solution?

**Comment by doxxx** [comment]
Actually, my problem is slightly different.

I have a worker binary that starts two worker pools, and I run multiple instances of this worker binary. If one of my jobs fails (i.e. returns an error), then I see this in the console of one of the workers:

```
ERROR: requeuer.process.dead - no job name
```

In the web UI, the failed job appears in the dead jobs queue with the following error:

```
unknown job when requeueing
```

**Comment by doxxx** [comment]
This happens even if I only have one worker binary.

**Comment by manojkumar195** [comment]
Has any solution been found for this issue ? I am also encountering the same problem.

**Comment by kilianw** [comment]
In case anyone encounters this, the solution for me was to ensure the two redis pools have different DialClientName and namespaces.

**Comment by chrisandrews7** [comment]
This worked for me by just having unique namespaces for the pools. Didnt need to have different DialClientNames.
