### ISSUE TITLE
Feature request: Allow customization of failed job backoff period

### ISSUE THREAD

**Issue by jalkanen** [gocraft/work#11]
Currently the worker does (numfails^4 + random constant). The 4th power grows extremely quickly for some use cases, and I'd like to have basically my own function to handle the backoff period.

A job for JobOptions perhaps?

**Comment by cypriss** [comment]
@jalkanen How many failures are you looking to support? The 4th power does grow quickly but is not insane for failures < 20 or 30. 

What backoff sequence would you want?

**Comment by jalkanen** [comment]
I'd like to have a capped Fibonacci sequence that terminates after a tunable N minute period, where N is dependent on the job itself.

**Comment by cypriss** [comment]
I'd be open to a PR that implements this as a JobOptions

**Comment by cypriss** [comment]
@jalkanen thx
