### ISSUE TITLE
Update to cron v3 

### ISSUE THREAD

**Issue by robfig** [gocraft/work#135]
I see you use the robfig/cron package, and I don't see any go.mod file that pins you to a specific version. I'm not sure if you have some other mechanism to get a specific revision, but I wanted to alert you that if you use "go get", I'm planning to push a backwards incompatible change, to bump the default version from v1 to v3.

Ref:
https://groups.google.com/forum/m/#!topic/golang-nuts/elraGIpy52Q

Happy to hear feedback on the issue:
robfig/cron#213

Thanks

**Comment by grv231** [comment]
Facing the same issue. Any update?

**Comment by robfig** [comment]
Since gocraft is a library, as long as the end users specify their own go.mod that includes cron v1, everything should work. 

I think this command will do it (untested):
```
  go mod edit -require=github.com/robfig/cron@v1
```

**Comment by grv231** [comment]
Yeah, for now, iI checked out the V1 branch in the robfig/cron folder to help run `go get` for gocraft/work which worked. But it might be worth looking into correcting this for the future. I will try the steps you mentioned
