### ISSUE TITLE
Stop consuming when a large number of jobs enqueue instantly

### ISSUE THREAD

**Issue by rush24** [gocraft/work#137]
In my testing, the worker stop consuming job when a a large number of jobs(4k in seconds) enqueue instantly. the web ui show: 
`2 queue(s) with a total of 4113 item(s) queued.`
`2 Worker process(es). 20 active worker(s) out of 20.`
All workers show busy status but just hung there unless i restart the consermer and it'll handling jobs again for about 1k and hung there again, i have to restart again and again...

**Comment by rush24** [comment]
@tylerb @cypriss

**Comment by kalyan-ksr** [comment]
Hey @rush24, how did you resolve this issue?

**Comment by miftahunajattiket** [comment]
Hi @rush24 how did you resolve the issue?
