### ISSUE TITLE
Worker consumes a job more then expected

### ISSUE THREAD

**Issue by adzimzf** [gocraft/work#148]
We push a job to `gocraft/work` use `EnqueuInUniqueByKey`.  we enqueue a unique job to running 5 minutes after it enqueued. Everything works like a charm until several days ago somehow the worker consumed multiple jobs with the same unique job at the same time. around 1K jobs are consumed for 30 minutes.

Anyone has experienced that case?

**Comment by mmacheerpuppy** [comment]
@adzimzf Hey! Which release do you use for your Gocraft library? Curious as the latest master branch seems to be bugged, and the EnqueueInUniqueByKey method doesn't seem to exist on the latest release.

**Comment by nghianguyen1tiki** [comment]
yeah, me too. enqueue onces, executed twice!
