### ISSUE TITLE
Can I start two processes to read one redis instance?

### ISSUE THREAD

**Issue by sillydong** [gocraft/work#19]
I want to start two processes to read one redis instance to ensure there is at least one process can handle queue. I wonder if this could cause one job to be run two times in different processes?

Thanks!

**Comment by cypriss** [comment]
@sillydong It will only be run once [a]. We use atomic redis operations that ensure this. This library is designed to handle multiple processes as you described.

[a] Technically it's at least once, but we try really hard to do exactly once. For instance, if your go program crashes RIGHT after processing a job, gocraft/work won't know if the job is done, so it will try again.

**Comment by sillydong** [comment]
Great! Thanks!
