### ISSUE TITLE
How can I send an complicated object to queue?

### ISSUE THREAD

**Issue by iamatsundere** [gocraft/work#191]
Hi, I sent my parameters to the queue with a command
`enqueuer.Enqueue("upload", work.Q{"data": dataset})`
where dataset is a bytes array.

But when I receive it in the process function, when I call job,Args["data"], my data is broken.

So how can I fix that or how can I do that?

Thank you.

**Comment by edalford11** [comment]
It's standard for job processing frameworks to not allow complex objects like this as parameters. If your data parameter is too large to break down into individual parameters, I would suggest sending your `data` as a json string and then parsing it in the job.

**Comment by iamatsundere** [comment]
Sorry for late reply, I got it. Thanks!
