### ISSUE TITLE
Feature Request: Retry job after some time of fail

### ISSUE THREAD

**Issue by virtax** [gocraft/work#23]

**Comment by cypriss** [comment]
@virtax Gocraft/work has retries built in. You can specify the number of times you want to retry. If you want to use a diff strategy, someone recently contributed a way to do that.

**Comment by virtax** [comment]
@cypriss How I can retry job after 60 seconds of fail first one? Do you have any specific parameters or functions for this case?

**Comment by cypriss** [comment]
@virtax You'll want to use the Backoff param in the JobOptions. You'll pass it a function that can return 60 to retry every 60 seconds. For an example of this, take a look at this test: https://github.com/gocraft/work/commit/8aaf0188a943df358f7a09ce48aff0f2318efb5b#diff-f9b84a9e0c0f3043ef9958a5c3ae2746R200

**Comment by virtax** [comment]
Will try, thank you.
