### ISSUE TITLE
Wait for job to complete

### ISSUE THREAD

**Issue by leandermelms** [gocraft/work#37]
Hi,

I'm starting jobs with: 

```go
_, err := enqueuer.Enqueue("handle_tika", work.Q{"pdf": bundle[0], "xml": bundle[1]})
if err != nil {
    log.Fatal(err)
}
```

this is called multiple times. I'd like to enque the jobs but let each of them wait for the running job. How can I achieve that?

**Comment by shdunning** [comment]
Hey @leandermelms -- 

I just added a {{MaxConcurrency}} job option, which allows you to control the max number of jobs in flight for that job type across WorkerPool processes. So using your example above, you would do something like the following when declaring the job type for {{handle_tika}} to ensure that there is never more than 1 {{handle_tika}} job running at a time:

```go
worker_pool.JobWithOptions("handle_tika", JobOptions{MaxConcurrency: 1}, (*Context).WorkFxn)
```

Hope this helps,

-- Shaun

**Comment by leandermelms** [comment]
Thank you so much @shdunning this was just what I was looking for. I wrote a hackerish improvisation which only submits a new job to the pool if the last one was successful but this is much better of course.
