### ISSUE TITLE
How to return a result to the caller in the job worker?

### ISSUE THREAD

**Issue by listeng** [gocraft/work#62]
Are there any function like this? Example:

//-----------------
//the caller:

job, err := enqueuer.Enqueue("add", work.Q{"a": 1, "b": 2})
...
result := job.GetResult()

//---------------------------
//and the worker:

pool.Job("add", (*Context).Add)
...
func (c *Context) Add(job *work.Job) error {
        a := job.ArgInt("a")
        b := job.ArgInt("b")

        resultAplusB := a + b
        // how to return this value of resultAplusB

	return nil
}

Thanks.

**Comment by austintaylor** [comment]
No, this is not something it is designed to do
