### ISSUE TITLE
Check Redis pool connection for error

### ISSUE THREAD

**Issue by ianwalter** [gocraft/work#8]
I'm running into `runtime error: invalid memory address or nil pointer dereference` and I think it's because Enqueue doesn't check to see if the connection it receives from the Redis pool is of type `errorConnection`, for example here:
https://github.com/gocraft/work/blob/master/enqueue.go#L46
I can submit a PR to add this check.

**Comment by ianwalter** [comment]
My error has nothing to do with this actually, but would checking conn.Err() still be a good idea?

**Comment by cypriss** [comment]
Glad to hear you worked it out.

Re: checking conn.Err() explicitly, I don't think it's necessary because Do will also return an error on the broken connection.

**Comment by cypriss** [comment]
I did this to hopefully make this more helpful for others in the future:  adc78a0ed73aee9382cad6fa7e15235ee030357c
