### ISSUE TITLE
ERROR: requeuer.process.dead - no job name

### ISSUE THREAD

**Issue by timsayshey** [gocraft/work#86]
After enqueuing a job to run after waiting 5 seconds, I get this error and my job doesn't run:
`ERROR: requeuer.process.dead - no job name`

What is the best way to troubleshoot this?

**Comment by timpwbaker** [comment]
What was the answer here? I have the same issue

**Comment by timsayshey** [comment]
Sorry, I wish I could remember but this was months ago. I think it was a configuration issue on my end. Either that or an update to the gocraft package was the fix. If you search the repo, you'll see where the error message is happening:
https://github.com/gocraft/work/search?q=%22no+job+name%22&unscoped_q=%22no+job+name%22

Hope that helps :)

**Comment by timpwbaker** [comment]
No worries! Thanks.
